# encoding: utf-8

##
# This file is auto-generated. DO NOT EDIT!
#
require 'protobuf'


##
# Imports
#
require 'google/protobuf/descriptor.pb'


##
# Enum Classes
#
class ENetworkDisconnectionReason < ::Protobuf::Enum
  define :NETWORK_DISCONNECT_INVALID, 0
  define :NETWORK_DISCONNECT_SHUTDOWN, 1
  define :NETWORK_DISCONNECT_DISCONNECT_BY_USER, 2
  define :NETWORK_DISCONNECT_DISCONNECT_BY_SERVER, 3
  define :NETWORK_DISCONNECT_LOST, 4
  define :NETWORK_DISCONNECT_OVERFLOW, 5
  define :NETWORK_DISCONNECT_STEAM_BANNED, 6
  define :NETWORK_DISCONNECT_STEAM_INUSE, 7
  define :NETWORK_DISCONNECT_STEAM_TICKET, 8
  define :NETWORK_DISCONNECT_STEAM_LOGON, 9
  define :NETWORK_DISCONNECT_STEAM_AUTHCANCELLED, 10
  define :NETWORK_DISCONNECT_STEAM_AUTHALREADYUSED, 11
  define :NETWORK_DISCONNECT_STEAM_AUTHINVALID, 12
  define :NETWORK_DISCONNECT_STEAM_VACBANSTATE, 13
  define :NETWORK_DISCONNECT_STEAM_LOGGED_IN_ELSEWHERE, 14
  define :NETWORK_DISCONNECT_STEAM_VAC_CHECK_TIMEDOUT, 15
  define :NETWORK_DISCONNECT_STEAM_DROPPED, 16
  define :NETWORK_DISCONNECT_STEAM_OWNERSHIP, 17
  define :NETWORK_DISCONNECT_SERVERINFO_OVERFLOW, 18
  define :NETWORK_DISCONNECT_TICKMSG_OVERFLOW, 19
  define :NETWORK_DISCONNECT_STRINGTABLEMSG_OVERFLOW, 20
  define :NETWORK_DISCONNECT_DELTAENTMSG_OVERFLOW, 21
  define :NETWORK_DISCONNECT_TEMPENTMSG_OVERFLOW, 22
  define :NETWORK_DISCONNECT_SOUNDSMSG_OVERFLOW, 23
  define :NETWORK_DISCONNECT_SNAPSHOTOVERFLOW, 24
  define :NETWORK_DISCONNECT_SNAPSHOTERROR, 25
  define :NETWORK_DISCONNECT_RELIABLEOVERFLOW, 26
  define :NETWORK_DISCONNECT_BADDELTATICK, 27
  define :NETWORK_DISCONNECT_NOMORESPLITS, 28
  define :NETWORK_DISCONNECT_TIMEDOUT, 29
  define :NETWORK_DISCONNECT_DISCONNECTED, 30
  define :NETWORK_DISCONNECT_LEAVINGSPLIT, 31
  define :NETWORK_DISCONNECT_DIFFERENTCLASSTABLES, 32
  define :NETWORK_DISCONNECT_BADRELAYPASSWORD, 33
  define :NETWORK_DISCONNECT_BADSPECTATORPASSWORD, 34
  define :NETWORK_DISCONNECT_HLTVRESTRICTED, 35
  define :NETWORK_DISCONNECT_NOSPECTATORS, 36
  define :NETWORK_DISCONNECT_HLTVUNAVAILABLE, 37
  define :NETWORK_DISCONNECT_HLTVSTOP, 38
  define :NETWORK_DISCONNECT_KICKED, 39
  define :NETWORK_DISCONNECT_BANADDED, 40
  define :NETWORK_DISCONNECT_KICKBANADDED, 41
  define :NETWORK_DISCONNECT_HLTVDIRECT, 42
  define :NETWORK_DISCONNECT_PURESERVER_CLIENTEXTRA, 43
  define :NETWORK_DISCONNECT_PURESERVER_MISMATCH, 44
  define :NETWORK_DISCONNECT_USERCMD, 45
  define :NETWORK_DISCONNECT_REJECTED_BY_GAME, 46
  define :NETWORK_DISCONNECT_MESSAGE_PARSE_ERROR, 47
  define :NETWORK_DISCONNECT_INVALID_MESSAGE_ERROR, 48
  define :NETWORK_DISCONNECT_BAD_SERVER_PASSWORD, 49
  define :NETWORK_DISCONNECT_DIRECT_CONNECT_RESERVATION, 50
  define :NETWORK_DISCONNECT_CONNECTION_FAILURE, 51
  define :NETWORK_DISCONNECT_NO_PEER_GROUP_HANDLERS, 52
  define :NETWORK_DISCONNECT_RECONNECTION, 53
  define :NETWORK_DISCONNECT_CONNECTION_CLOSING, 54
  define :NETWORK_DISCONNECT_NO_GOTV_RELAYS_AVAILABLE, 55
  define :NETWORK_DISCONNECT_SESSION_MIGRATED, 56
  define :NETWORK_DISCONNECT_VERYLARGETRANSFEROVERFLOW, 57
  define :NETWORK_DISCONNECT_SENDNETOVERFLOW, 58
  define :NETWORK_DISCONNECT_PLAYER_REMOVED_FROM_HOST_SESSION, 59
end


##
# File Options
#
set_option :cc_generic_services, false


##
# Extended Message Fields
#
class ::Google::Protobuf::EnumValueOptions < ::Protobuf::Message
  optional :string, :".network_connection_token", 50500, :extension => true
end

